package com.orbit.spatialjournal.ai

import com.orbit.spatialjournal.core.model.*
import com.orbit.spatialjournal.core.util.DateTimeUtils
import com.orbit.spatialjournal.core.util.GeoMath
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Fully on-device implementation of [AIAssistantProvider]. Every output is generated by
 * aggregating and templating the user's real Memory data — nothing is fabricated, and
 * nothing ever leaves the device. This is what "Daily/Weekly/Monthly Recap" and "AI Story
 * Builder" actually run on by default.
 */
@Singleton
class LocalRuleBasedAssistant @Inject constructor() : AIAssistantProvider {

    override fun buildDayRecap(memories: List<Memory>, dayLabel: String, fromEpoch: Long, toEpoch: Long): RecapData =
        buildRecap(memories, dayLabel, fromEpoch, toEpoch)

    override fun buildRangeRecap(memories: List<Memory>, periodLabel: String, fromEpoch: Long, toEpoch: Long): RecapData =
        buildRecap(memories, periodLabel, fromEpoch, toEpoch)

    private fun buildRecap(memories: List<Memory>, periodLabel: String, fromEpoch: Long, toEpoch: Long): RecapData {
        if (memories.isEmpty()) {
            return RecapData(
                periodLabel = periodLabel, fromDate = fromEpoch, toDate = toEpoch,
                placesVisited = emptyList(), memoryCount = 0, topTags = emptyList(),
                mostCapturedHour = null, highlightMemoryIds = emptyList(),
                narrative = "" // UI shows a localized empty-state string instead of narrative text.
            )
        }

        val places = memories.mapNotNull { it.placeName ?: it.city }.distinct()
        val topTags = memories.flatMap { it.tags }.groupingBy { it }.eachCount()
            .entries.sortedByDescending { it.value }.take(5).map { it.key }
        val mostCapturedHour = memories
            .map { DateTimeUtils.toLocalDateTime(it.timestamp).hour }
            .groupingBy { it }.eachCount().maxByOrNull { it.value }?.key

        // Highlights: prefer favorites, then photos/videos with descriptions, then earliest/latest of the day.
        val highlights = (memories.filter { it.isFavorite } +
            memories.filter { it.type == MemoryType.PHOTO || it.type == MemoryType.VIDEO } +
            listOf(memories.minByOrNull { it.timestamp }, memories.maxByOrNull { it.timestamp }).filterNotNull())
            .distinctBy { it.id }.take(6).map { it.id }

        val narrative = buildString {
            append("$periodLabel: ${memories.size} memories")
            if (places.isNotEmpty()) append(" across ${places.size} place(s) — ${places.take(3).joinToString(", ")}")
            if (topTags.isNotEmpty()) append(". Top topics: ${topTags.joinToString(", ")}")
        }

        return RecapData(
            periodLabel = periodLabel, fromDate = fromEpoch, toDate = toEpoch,
            placesVisited = places, memoryCount = memories.size, topTags = topTags,
            mostCapturedHour = mostCapturedHour, highlightMemoryIds = highlights, narrative = narrative
        )
    }

    override fun buildTripSummary(memories: List<Memory>, tripName: String): GeneratedStory {
        val sorted = memories.sortedBy { it.timestamp }
        val places = sorted.mapNotNull { it.placeName ?: it.city }.distinct()
        val sections = places.map { place ->
            val placeMemories = sorted.filter { it.placeName == place || it.city == place }
            StorySection(
                heading = place,
                body = "${placeMemories.size} memories, ${placeMemories.count { it.type == MemoryType.PHOTO }} photos.",
                memoryIds = placeMemories.map { it.id }
            )
        }
        val intro = if (sorted.isEmpty()) "" else
            "$tripName spans ${places.size} place(s) from ${DateTimeUtils.formatShortDate(sorted.first().timestamp)} " +
                "to ${DateTimeUtils.formatShortDate(sorted.last().timestamp)}, with ${sorted.size} memories captured."

        return GeneratedStory(title = tripName, introduction = intro, sections = sections, highlightPlaceIds = places)
    }

    override fun buildStory(memories: List<Memory>, title: String): GeneratedStory {
        val sorted = memories.sortedBy { it.timestamp }
        val byDay = sorted.groupBy { DateTimeUtils.startOfDay(it.timestamp) }
        val sections = byDay.entries.sortedBy { it.key }.map { (dayStart, dayMemories) ->
            StorySection(
                heading = DateTimeUtils.formatShortDate(dayStart),
                body = dayMemories.joinToString(" · ") { it.title }.take(240),
                memoryIds = dayMemories.map { it.id }
            )
        }
        val intro = if (sorted.isEmpty()) "" else
            "$title — ${sorted.size} memories across ${byDay.size} day(s)."
        val places = sorted.mapNotNull { it.placeName }.distinct()
        return GeneratedStory(title = title, introduction = intro, sections = sections, highlightPlaceIds = places)
    }

    override fun findRelated(target: Memory, candidates: List<Memory>, maxResults: Int): List<Memory> {
        val targetTagSet = target.tags.toSet()
        return candidates.filter { it.id != target.id }
            .map { candidate ->
                var score = 0.0
                if (candidate.tripId != null && candidate.tripId == target.tripId) score += 3.0
                if (candidate.placeName != null && candidate.placeName == target.placeName) score += 2.5
                if (DateTimeUtils.isSameCalendarDay(candidate.timestamp, target.timestamp)) score += 2.0
                val sharedTags = targetTagSet.intersect(candidate.tags.toSet()).size
                score += sharedTags * 1.2
                if (target.location != null && candidate.location != null) {
                    val distance = GeoMath.distanceMeters(target.location, candidate.location)
                    if (distance < 300) score += 1.5
                }
                candidate to score
            }
            .filter { it.second > 0 }
            .sortedByDescending { it.second }
            .take(maxResults)
            .map { it.first }
    }
}
